var site_data = {
        "starting_url":"http://jason-cowan.com",
        "domain":"http://jason-cowan.com",
        "total_urls":47,
        "total_time":20431,
        "total_misspellings":122,
        "total_same_domain_pages":8,
        "total_same_domain_urls":34,
        "total_images":25,
	"urls":[ 
		{
                    "url":"http://m.gamescom-cologne.com/en/gamescom/index.php",
                    "http_code":404,
		    "direct_parent":"http://m.gamescom-cologne.com",
                    "content_type":"text/html; charset=UTF-8",
                    "retrieval_time":458,
                    "io_error":false,
                    "malformed_url":false,
                    "timeout_error":false,
                    "casting_error":false,
                    "content_length":4662,
                    "last_modified":0,
                    "referencing_urls":[
                                "http://m.gamescom-cologne.com"
                    ],
                    "html_asset":{
                            "document_type":"",
                            "title":"",
                            "description":"",
                            "misspellings":[],
                            "at_mentions":[],
                            "hash_tags":[],
                            "emails":[],
                            "deprecated_tags":[],
                            "poor_link_naming":[],
                            "inputs_no_labels":[
                            ],
                            "no_alt_text":[]
                        }

                }
                ,
		{
                    "url":"http://jason-cowan.com/resources/images/projects/mario-runs/deaths.png",
                    "http_code":200,
		    "direct_parent":"http://jason-cowan.com/projects/mario-runs.html",
                    "content_type":"image/png",
                    "retrieval_time":239,
                    "io_error":false,
                    "malformed_url":false,
                    "timeout_error":false,
                    "casting_error":false,
                    "content_length":336968,
                    "last_modified":1389855143000,
                    "referencing_urls":[
                                "http://jason-cowan.com/projects/mario-runs.html"
                    ],
                    "html_asset":null
                }
                ,
		{
                    "url":"https://github.com/jcow/Triple-Triad",
                    "http_code":200,
		    "direct_parent":"http://jason-cowan.com/projects.html",
                    "content_type":"text/html; charset=utf-8",
                    "retrieval_time":424,
                    "io_error":false,
                    "malformed_url":false,
                    "timeout_error":false,
                    "casting_error":false,
                    "content_length":32056,
                    "last_modified":0,
                    "referencing_urls":[
                                "http://jason-cowan.com/projects.html"
                    ],
                    "html_asset":{
                            "document_type":"",
                            "title":"",
                            "description":"",
                            "misspellings":[],
                            "at_mentions":[],
                            "hash_tags":[],
                            "emails":[],
                            "deprecated_tags":[],
                            "poor_link_naming":[],
                            "inputs_no_labels":[
                            ],
                            "no_alt_text":[]
                        }

                }
                ,
		{
                    "url":"https://github.com/jcow/Word-Ladder",
                    "http_code":200,
		    "direct_parent":"http://jason-cowan.com/projects.html",
                    "content_type":"text/html; charset=utf-8",
                    "retrieval_time":916,
                    "io_error":false,
                    "malformed_url":false,
                    "timeout_error":false,
                    "casting_error":false,
                    "content_length":30693,
                    "last_modified":0,
                    "referencing_urls":[
                                "http://jason-cowan.com/projects.html"
                    ],
                    "html_asset":{
                            "document_type":"",
                            "title":"",
                            "description":"",
                            "misspellings":[],
                            "at_mentions":[],
                            "hash_tags":[],
                            "emails":[],
                            "deprecated_tags":[],
                            "poor_link_naming":[],
                            "inputs_no_labels":[
                            ],
                            "no_alt_text":[]
                        }

                }
                ,
		{
                    "url":"http://jason-cowan.com/resources/images/projects/word-ladder/chart-which.png",
                    "http_code":200,
		    "direct_parent":"http://jason-cowan.com/projects/word-ladder.html",
                    "content_type":"image/png",
                    "retrieval_time":264,
                    "io_error":false,
                    "malformed_url":false,
                    "timeout_error":false,
                    "casting_error":false,
                    "content_length":893174,
                    "last_modified":1389855143000,
                    "referencing_urls":[
                                "http://jason-cowan.com/projects/word-ladder.html"
                    ],
                    "html_asset":null
                }
                ,
		{
                    "url":"http://jason-cowan.com/resources/utilities/jquery/jquery-1.10.2.min.js",
                    "http_code":200,
		    "direct_parent":"http://jason-cowan.com",
                    "content_type":"application/javascript",
                    "retrieval_time":263,
                    "io_error":false,
                    "malformed_url":false,
                    "timeout_error":false,
                    "casting_error":false,
                    "content_length":93106,
                    "last_modified":1389855143000,
                    "referencing_urls":[
                                "http://jason-cowan.com",
                                "http://jason-cowan.com/projects.html",
                                "http://jason-cowan.com/resume.html",
                                "http://jason-cowan.com/projects/mario-runs.html",
                                "http://jason-cowan.com/projects/immuno.html",
                                "http://jason-cowan.com/projects/word-ladder.html",
                                "http://jason-cowan.com/projects/needleman-wunsch.html",
                                "http://jason-cowan.com/projects/triple-triad.html"
                    ],
                    "html_asset":null
                }
                ,
		{
                    "url":"http://jason-cowan.com/resources/images/projects/triple_triad/screen2.png",
                    "http_code":200,
		    "direct_parent":"http://jason-cowan.com/projects/triple-triad.html",
                    "content_type":"image/png",
                    "retrieval_time":250,
                    "io_error":false,
                    "malformed_url":false,
                    "timeout_error":false,
                    "casting_error":false,
                    "content_length":510802,
                    "last_modified":1389855143000,
                    "referencing_urls":[
                                "http://jason-cowan.com/projects/triple-triad.html"
                    ],
                    "html_asset":null
                }
                ,
		{
                    "url":"https://github.com/jcow",
                    "http_code":200,
		    "direct_parent":"http://jason-cowan.com",
                    "content_type":"text/html; charset=utf-8",
                    "retrieval_time":787,
                    "io_error":false,
                    "malformed_url":false,
                    "timeout_error":false,
                    "casting_error":false,
                    "content_length":19690,
                    "last_modified":0,
                    "referencing_urls":[
                                "http://jason-cowan.com",
                                "http://jason-cowan.com/projects.html",
                                "http://jason-cowan.com/resume.html",
                                "http://jason-cowan.com/projects/mario-runs.html",
                                "http://jason-cowan.com/projects/immuno.html",
                                "http://jason-cowan.com/projects/word-ladder.html",
                                "http://jason-cowan.com/projects/needleman-wunsch.html",
                                "http://jason-cowan.com/projects/triple-triad.html"
                    ],
                    "html_asset":{
                            "document_type":"",
                            "title":"",
                            "description":"",
                            "misspellings":[],
                            "at_mentions":[],
                            "hash_tags":[],
                            "emails":[],
                            "deprecated_tags":[],
                            "poor_link_naming":[],
                            "inputs_no_labels":[
                            ],
                            "no_alt_text":[]
                        }

                }
                ,
		{
                    "url":"http://jason-cowan.com/resources/images/projects/immuno/green1.png",
                    "http_code":200,
		    "direct_parent":"http://jason-cowan.com/projects/immuno.html",
                    "content_type":"image/png",
                    "retrieval_time":246,
                    "io_error":false,
                    "malformed_url":false,
                    "timeout_error":false,
                    "casting_error":false,
                    "content_length":308667,
                    "last_modified":1389855143000,
                    "referencing_urls":[
                                "http://jason-cowan.com/projects/immuno.html"
                    ],
                    "html_asset":null
                }
                ,
		{
                    "url":"http://jason-cowan.com/resources/images/projects/mario-runs/speed_vs_deaths.png",
                    "http_code":200,
		    "direct_parent":"http://jason-cowan.com/projects/mario-runs.html",
                    "content_type":"image/png",
                    "retrieval_time":254,
                    "io_error":false,
                    "malformed_url":false,
                    "timeout_error":false,
                    "casting_error":false,
                    "content_length":18873,
                    "last_modified":1389855143000,
                    "referencing_urls":[
                                "http://jason-cowan.com/projects/mario-runs.html"
                    ],
                    "html_asset":null
                }
                ,
		{
                    "url":"https://github.com/jcow/Needleman-Wunsch",
                    "http_code":200,
		    "direct_parent":"http://jason-cowan.com/projects.html",
                    "content_type":"text/html; charset=utf-8",
                    "retrieval_time":324,
                    "io_error":false,
                    "malformed_url":false,
                    "timeout_error":false,
                    "casting_error":false,
                    "content_length":29096,
                    "last_modified":0,
                    "referencing_urls":[
                                "http://jason-cowan.com/projects.html"
                    ],
                    "html_asset":{
                            "document_type":"",
                            "title":"",
                            "description":"",
                            "misspellings":[],
                            "at_mentions":[],
                            "hash_tags":[],
                            "emails":[],
                            "deprecated_tags":[],
                            "poor_link_naming":[],
                            "inputs_no_labels":[
                            ],
                            "no_alt_text":[]
                        }

                }
                ,
		{
                    "url":"http://jason-cowan.com/resources/images/homepage/mario.png",
                    "http_code":200,
		    "direct_parent":"http://jason-cowan.com",
                    "content_type":"image/png",
                    "retrieval_time":227,
                    "io_error":false,
                    "malformed_url":false,
                    "timeout_error":false,
                    "casting_error":false,
                    "content_length":263874,
                    "last_modified":1389855143000,
                    "referencing_urls":[
                                "http://jason-cowan.com"
                    ],
                    "html_asset":null
                }
                ,
		{
                    "url":"http://jason-cowan.com/resources/images/projects/word-ladder/node-graph.png",
                    "http_code":200,
		    "direct_parent":"http://jason-cowan.com/projects/word-ladder.html",
                    "content_type":"image/png",
                    "retrieval_time":242,
                    "io_error":false,
                    "malformed_url":false,
                    "timeout_error":false,
                    "casting_error":false,
                    "content_length":125779,
                    "last_modified":1389855143000,
                    "referencing_urls":[
                                "http://jason-cowan.com/projects/word-ladder.html"
                    ],
                    "html_asset":null
                }
                ,
		{
                    "url":"http://jason-cowan.com/resources/images/projects/needleman-wunsch/example.png",
                    "http_code":200,
		    "direct_parent":"http://jason-cowan.com/projects/needleman-wunsch.html",
                    "content_type":"image/png",
                    "retrieval_time":251,
                    "io_error":false,
                    "malformed_url":false,
                    "timeout_error":false,
                    "casting_error":false,
                    "content_length":24593,
                    "last_modified":1389855143000,
                    "referencing_urls":[
                                "http://jason-cowan.com/projects/needleman-wunsch.html"
                    ],
                    "html_asset":null
                }
                ,
		{
                    "url":"http://jason-cowan.com",
                    "http_code":200,
		    "direct_parent":"",
                    "content_type":"text/html",
                    "retrieval_time":456,
                    "io_error":false,
                    "malformed_url":false,
                    "timeout_error":false,
                    "casting_error":false,
                    "content_length":2977,
                    "last_modified":1389855143000,
                    "referencing_urls":[
                                "http://jason-cowan.com/projects.html",
                                "http://jason-cowan.com/resume.html",
                                "http://jason-cowan.com/projects/mario-runs.html",
                                "http://jason-cowan.com/projects/immuno.html",
                                "http://jason-cowan.com/projects/word-ladder.html",
                                "http://jason-cowan.com/projects/needleman-wunsch.html",
                                "http://jason-cowan.com/projects/triple-triad.html"
                    ],
                    "html_asset":{
                            "document_type":"&lt;!DOCTYPE html&gt;",
                            "title":"Welcome",
                            "description":"",
                            "misspellings":["Cowan","Todos","CSS","Cowan","Missoula","Immunofluorescence","Cowan"],
                            "at_mentions":[],
                            "hash_tags":[],
                            "emails":[],
                            "deprecated_tags":[],
                            "poor_link_naming":[],
                            "inputs_no_labels":[
                            ],
                            "no_alt_text":["http://jason-cowan.com/resources/images/cat.png","http://jason-cowan.com/resources/images/li.png","http://jason-cowan.com/resources/images/homepage/mario.png","http://jason-cowan.com/resources/images/homepage/red2.png","http://jason-cowan.com/resources/images/homepage/chart-which.png"]
                        }

                }
                ,
		{
                    "url":"http://stabyourself.net/",
                    "http_code":200,
		    "direct_parent":"http://jason-cowan.com/projects/mario-runs.html",
                    "content_type":"text/html",
                    "retrieval_time":426,
                    "io_error":false,
                    "malformed_url":false,
                    "timeout_error":false,
                    "casting_error":false,
                    "content_length":-1,
                    "last_modified":0,
                    "referencing_urls":[
                                "http://jason-cowan.com/projects/mario-runs.html"
                    ],
                    "html_asset":{
                            "document_type":"",
                            "title":"",
                            "description":"",
                            "misspellings":[],
                            "at_mentions":[],
                            "hash_tags":[],
                            "emails":[],
                            "deprecated_tags":[],
                            "poor_link_naming":[],
                            "inputs_no_labels":[
                            ],
                            "no_alt_text":[]
                        }

                }
                ,
		{
                    "url":"http://jason-cowan.com/projects/triple-triad.html",
                    "http_code":200,
		    "direct_parent":"http://jason-cowan.com/projects.html",
                    "content_type":"text/html",
                    "retrieval_time":116,
                    "io_error":false,
                    "malformed_url":false,
                    "timeout_error":false,
                    "casting_error":false,
                    "content_length":3288,
                    "last_modified":1389855143000,
                    "referencing_urls":[
                                "http://jason-cowan.com/projects.html"
                    ],
                    "html_asset":{
                            "document_type":"&lt;!DOCTYPE html&gt;",
                            "title":"Triple Triad A.B. Pruning",
                            "description":"",
                            "misspellings":["Cowan","A.B","tac","AI","gameplay","AB","Screenshots","Cowan"],
                            "at_mentions":[],
                            "hash_tags":[],
                            "emails":[],
                            "deprecated_tags":[],
                            "poor_link_naming":[],
                            "inputs_no_labels":[
                            ],
                            "no_alt_text":["http://jason-cowan.com/resources/images/cat.png","http://jason-cowan.com/resources/images/li.png","http://jason-cowan.com/resources/images/projects/triple_triad/screen1.png","http://jason-cowan.com/resources/images/projects/triple_triad/screen2.png","http://jason-cowan.com/resources/images/projects/triple_triad/stats.png"]
                        }

                }
                ,
		{
                    "url":"http://jason-cowan.com/resources/images/cat_dark.png",
                    "http_code":200,
		    "direct_parent":"http://jason-cowan.com/projects.html",
                    "content_type":"image/png",
                    "retrieval_time":126,
                    "io_error":false,
                    "malformed_url":false,
                    "timeout_error":false,
                    "casting_error":false,
                    "content_length":1714,
                    "last_modified":1389855143000,
                    "referencing_urls":[
                                "http://jason-cowan.com/projects.html",
                                "http://jason-cowan.com/projects.html",
                                "http://jason-cowan.com/projects.html",
                                "http://jason-cowan.com/projects.html",
                                "http://jason-cowan.com/projects.html",
                                "http://jason-cowan.com/projects/immuno.html"
                    ],
                    "html_asset":null
                }
                ,
		{
                    "url":"http://jason-cowan.com/resources/images/projects/mario-runs/time_vs_speed.png",
                    "http_code":200,
		    "direct_parent":"http://jason-cowan.com/projects/mario-runs.html",
                    "content_type":"image/png",
                    "retrieval_time":277,
                    "io_error":false,
                    "malformed_url":false,
                    "timeout_error":false,
                    "casting_error":false,
                    "content_length":29750,
                    "last_modified":1389855143000,
                    "referencing_urls":[
                                "http://jason-cowan.com/projects/mario-runs.html"
                    ],
                    "html_asset":null
                }
                ,
		{
                    "url":"http://www.youtube.com/watch?v=cTiJaWCaKas",
                    "http_code":200,
		    "direct_parent":"http://jason-cowan.com/projects/mario-runs.html",
                    "content_type":"text/html; charset=utf-8",
                    "retrieval_time":139,
                    "io_error":false,
                    "malformed_url":false,
                    "timeout_error":false,
                    "casting_error":false,
                    "content_length":-1,
                    "last_modified":0,
                    "referencing_urls":[
                                "http://jason-cowan.com/projects/mario-runs.html"
                    ],
                    "html_asset":{
                            "document_type":"",
                            "title":"",
                            "description":"",
                            "misspellings":[],
                            "at_mentions":[],
                            "hash_tags":[],
                            "emails":[],
                            "deprecated_tags":[],
                            "poor_link_naming":[],
                            "inputs_no_labels":[
                            ],
                            "no_alt_text":[]
                        }

                }
                ,
		{
                    "url":"http://jason-cowan.com/resources/images/cat.png",
                    "http_code":200,
		    "direct_parent":"http://jason-cowan.com",
                    "content_type":"image/png",
                    "retrieval_time":123,
                    "io_error":false,
                    "malformed_url":false,
                    "timeout_error":false,
                    "casting_error":false,
                    "content_length":733,
                    "last_modified":1389855143000,
                    "referencing_urls":[
                                "http://jason-cowan.com",
                                "http://jason-cowan.com/projects.html",
                                "http://jason-cowan.com/resume.html",
                                "http://jason-cowan.com/projects/mario-runs.html",
                                "http://jason-cowan.com/projects/immuno.html",
                                "http://jason-cowan.com/projects/word-ladder.html",
                                "http://jason-cowan.com/projects/needleman-wunsch.html",
                                "http://jason-cowan.com/projects/triple-triad.html"
                    ],
                    "html_asset":null
                }
                ,
		{
                    "url":"http://jason-cowan.com/resources/images/projects/mario-runs/deaths_grouped.png",
                    "http_code":200,
		    "direct_parent":"http://jason-cowan.com/projects/mario-runs.html",
                    "content_type":"image/png",
                    "retrieval_time":256,
                    "io_error":false,
                    "malformed_url":false,
                    "timeout_error":false,
                    "casting_error":false,
                    "content_length":366326,
                    "last_modified":1389855143000,
                    "referencing_urls":[
                                "http://jason-cowan.com/projects/mario-runs.html"
                    ],
                    "html_asset":null
                }
                ,
		{
                    "url":"http://jason-cowan.com/projects/immuno.html",
                    "http_code":200,
		    "direct_parent":"http://jason-cowan.com",
                    "content_type":"text/html",
                    "retrieval_time":116,
                    "io_error":false,
                    "malformed_url":false,
                    "timeout_error":false,
                    "casting_error":false,
                    "content_length":3660,
                    "last_modified":1389855143000,
                    "referencing_urls":[
                                "http://jason-cowan.com",
                                "http://jason-cowan.com/projects.html"
                    ],
                    "html_asset":{
                            "document_type":"&lt;!DOCTYPE html&gt;",
                            "title":"I.L. Correction",
                            "description":"",
                            "misspellings":["Cowan","I.L","immunofluorescence","GitHub","Repo","GitHub","immunofluorescence","Immunoflourescence","Immunoflourescence","Immunoflourescence","Immunoflourescence","Immunoflourescence","Immunoflourescence","Cowan"],
                            "at_mentions":[],
                            "hash_tags":[],
                            "emails":[],
                            "deprecated_tags":[],
                            "poor_link_naming":[],
                            "inputs_no_labels":[
                            ],
                            "no_alt_text":["http://jason-cowan.com/resources/images/cat.png","http://jason-cowan.com/resources/images/li.png"]
                        }

                }
                ,
		{
                    "url":"http://jason-cowan.com/resources/images/projects/mario-runs/paths.png",
                    "http_code":200,
		    "direct_parent":"http://jason-cowan.com/projects/mario-runs.html",
                    "content_type":"image/png",
                    "retrieval_time":256,
                    "io_error":false,
                    "malformed_url":false,
                    "timeout_error":false,
                    "casting_error":false,
                    "content_length":2303443,
                    "last_modified":1389855143000,
                    "referencing_urls":[
                                "http://jason-cowan.com/projects/mario-runs.html"
                    ],
                    "html_asset":null
                }
                ,
		{
                    "url":"http://jason-cowan.com/resources/images/projects/triple_triad/screen1.png",
                    "http_code":200,
		    "direct_parent":"http://jason-cowan.com/projects/triple-triad.html",
                    "content_type":"image/png",
                    "retrieval_time":232,
                    "io_error":false,
                    "malformed_url":false,
                    "timeout_error":false,
                    "casting_error":false,
                    "content_length":470528,
                    "last_modified":1389855143000,
                    "referencing_urls":[
                                "http://jason-cowan.com/projects/triple-triad.html"
                    ],
                    "html_asset":null
                }
                ,
		{
                    "url":"http://jason-cowan.com/resources/images/homepage/red2.png",
                    "http_code":200,
		    "direct_parent":"http://jason-cowan.com",
                    "content_type":"image/png",
                    "retrieval_time":250,
                    "io_error":false,
                    "malformed_url":false,
                    "timeout_error":false,
                    "casting_error":false,
                    "content_length":93537,
                    "last_modified":1389855143000,
                    "referencing_urls":[
                                "http://jason-cowan.com"
                    ],
                    "html_asset":null
                }
                ,
		{
                    "url":"http://jason-cowan.com/projects.html",
                    "http_code":200,
		    "direct_parent":"http://jason-cowan.com",
                    "content_type":"text/html",
                    "retrieval_time":122,
                    "io_error":false,
                    "malformed_url":false,
                    "timeout_error":false,
                    "casting_error":false,
                    "content_length":3548,
                    "last_modified":1389855143000,
                    "referencing_urls":[
                                "http://jason-cowan.com",
                                "http://jason-cowan.com/resume.html",
                                "http://jason-cowan.com/projects/mario-runs.html",
                                "http://jason-cowan.com/projects/immuno.html",
                                "http://jason-cowan.com/projects/word-ladder.html",
                                "http://jason-cowan.com/projects/needleman-wunsch.html",
                                "http://jason-cowan.com/projects/triple-triad.html"
                    ],
                    "html_asset":{
                            "document_type":"&lt;!DOCTYPE html&gt;",
                            "title":"Projects",
                            "description":"",
                            "misspellings":["Cowan","Immunofluorescence","GitHub","Needleman","Wunsch","HTML","GitHub","HTML","GitHub","HTML","GitHub","HTML","GitHub","Cowan"],
                            "at_mentions":[],
                            "hash_tags":[],
                            "emails":[],
                            "deprecated_tags":[],
                            "poor_link_naming":[],
                            "inputs_no_labels":[
                            ],
                            "no_alt_text":["http://jason-cowan.com/resources/images/cat.png","http://jason-cowan.com/resources/images/li.png"]
                        }

                }
                ,
		{
                    "url":"http://jason-cowan.com/resources/images/projects/mario-runs/time_vs_deaths.png",
                    "http_code":200,
		    "direct_parent":"http://jason-cowan.com/projects/mario-runs.html",
                    "content_type":"image/png",
                    "retrieval_time":288,
                    "io_error":false,
                    "malformed_url":false,
                    "timeout_error":false,
                    "casting_error":false,
                    "content_length":19695,
                    "last_modified":1389855143000,
                    "referencing_urls":[
                                "http://jason-cowan.com/projects/mario-runs.html"
                    ],
                    "html_asset":null
                }
                ,
		{
                    "url":"http://jason-cowan.com/projects/mario-runs.html",
                    "http_code":200,
		    "direct_parent":"http://jason-cowan.com",
                    "content_type":"text/html",
                    "retrieval_time":129,
                    "io_error":false,
                    "malformed_url":false,
                    "timeout_error":false,
                    "casting_error":false,
                    "content_length":6519,
                    "last_modified":1389855143000,
                    "referencing_urls":[
                                "http://jason-cowan.com",
                                "http://jason-cowan.com/projects.html"
                    ],
                    "html_asset":{
                            "document_type":"&lt;!DOCTYPE html&gt;",
                            "title":"Mario Runs Visualization",
                            "description":"",
                            "misspellings":["Cowan","Stabyourself.net","Lua","Stabyourself.net","Stabyourself.net","Stabyourself.net","gamescom","Stabyourself.net","Screenshots","screenshots","colorized","Firebar","Firebar","Goomba","Goomba","Goomba","Goomba","Goomba","Goomba","Koopa","Troopa","Koopa","Troopa","Bowser","Cowan"],
                            "at_mentions":[],
                            "hash_tags":[],
                            "emails":[],
                            "deprecated_tags":[],
                            "poor_link_naming":[],
                            "inputs_no_labels":[
                            ],
                            "no_alt_text":["http://jason-cowan.com/resources/images/cat.png","http://jason-cowan.com/resources/images/li.png","http://jason-cowan.com/resources/images/projects/mario-runs/deaths_grouped.png"]
                        }

                }
                ,
		{
                    "url":"http://jason-cowan.com/resources/images/projects/immuno/red1.png",
                    "http_code":200,
		    "direct_parent":"http://jason-cowan.com/projects/immuno.html",
                    "content_type":"image/png",
                    "retrieval_time":234,
                    "io_error":false,
                    "malformed_url":false,
                    "timeout_error":false,
                    "casting_error":false,
                    "content_length":118882,
                    "last_modified":1389855143000,
                    "referencing_urls":[
                                "http://jason-cowan.com/projects/immuno.html"
                    ],
                    "html_asset":null
                }
                ,
		{
                    "url":"http://jason-cowan.com/resources/images/projects/immuno/green2.png",
                    "http_code":200,
		    "direct_parent":"http://jason-cowan.com/projects/immuno.html",
                    "content_type":"image/png",
                    "retrieval_time":261,
                    "io_error":false,
                    "malformed_url":false,
                    "timeout_error":false,
                    "casting_error":false,
                    "content_length":284448,
                    "last_modified":1389855143000,
                    "referencing_urls":[
                                "http://jason-cowan.com/projects/immuno.html"
                    ],
                    "html_asset":null
                }
                ,
		{
                    "url":"http://jason-cowan.com/resources/images/li.png",
                    "http_code":200,
		    "direct_parent":"http://jason-cowan.com",
                    "content_type":"image/png",
                    "retrieval_time":236,
                    "io_error":false,
                    "malformed_url":false,
                    "timeout_error":false,
                    "casting_error":false,
                    "content_length":684,
                    "last_modified":1389855143000,
                    "referencing_urls":[
                                "http://jason-cowan.com",
                                "http://jason-cowan.com/projects.html",
                                "http://jason-cowan.com/resume.html",
                                "http://jason-cowan.com/projects/mario-runs.html",
                                "http://jason-cowan.com/projects/immuno.html",
                                "http://jason-cowan.com/projects/word-ladder.html",
                                "http://jason-cowan.com/projects/needleman-wunsch.html",
                                "http://jason-cowan.com/projects/triple-triad.html"
                    ],
                    "html_asset":null
                }
                ,
		{
                    "url":"http://jason-cowan.com/resume.html",
                    "http_code":200,
		    "direct_parent":"http://jason-cowan.com",
                    "content_type":"text/html",
                    "retrieval_time":122,
                    "io_error":false,
                    "malformed_url":false,
                    "timeout_error":false,
                    "casting_error":false,
                    "content_length":4978,
                    "last_modified":1389855143000,
                    "referencing_urls":[
                                "http://jason-cowan.com",
                                "http://jason-cowan.com/projects.html",
                                "http://jason-cowan.com/projects/mario-runs.html",
                                "http://jason-cowan.com/projects/immuno.html",
                                "http://jason-cowan.com/projects/word-ladder.html",
                                "http://jason-cowan.com/projects/needleman-wunsch.html",
                                "http://jason-cowan.com/projects/triple-triad.html"
                    ],
                    "html_asset":{
                            "document_type":"&lt;!DOCTYPE html&gt;",
                            "title":"Resume",
                            "description":"",
                            "misspellings":["Cowan","Missoula","Missoula","SAIT","univerity","incrementally","systemCascade","App","Delevop","XNA","PHP","Lua","Haskell","HTML","CSS","Fortran","OCaml","SQL","CodeIgniter","PHP","MVC","Laravel","PHP","MVC","JQuery","JS","MVW","three.js","PHP","PHP","PHP","PHP","ORM","JUnit","XNA","Xbox","OpenGL","Cowan"],
                            "at_mentions":[],
                            "hash_tags":[],
                            "emails":[],
                            "deprecated_tags":[],
                            "poor_link_naming":[],
                            "inputs_no_labels":[
                            ],
                            "no_alt_text":["http://jason-cowan.com/resources/images/cat.png","http://jason-cowan.com/resources/images/li.png"]
                        }

                }
                ,
		{
                    "url":"http://jason-cowan.com/projects/needleman-wunsch.html",
                    "http_code":200,
		    "direct_parent":"http://jason-cowan.com/projects.html",
                    "content_type":"text/html",
                    "retrieval_time":231,
                    "io_error":false,
                    "malformed_url":false,
                    "timeout_error":false,
                    "casting_error":false,
                    "content_length":2028,
                    "last_modified":1389855143000,
                    "referencing_urls":[
                                "http://jason-cowan.com/projects.html"
                    ],
                    "html_asset":{
                            "document_type":"&lt;!DOCTYPE html&gt;",
                            "title":"Needleman-Wunsch",
                            "description":"",
                            "misspellings":["Cowan","Needleman","Wunsch","bioinformatics","Needleman","Wunsch","nucleotide","Screenshot","Cowan"],
                            "at_mentions":[],
                            "hash_tags":[],
                            "emails":[],
                            "deprecated_tags":[],
                            "poor_link_naming":[],
                            "inputs_no_labels":[
                            ],
                            "no_alt_text":["http://jason-cowan.com/resources/images/cat.png","http://jason-cowan.com/resources/images/li.png","http://jason-cowan.com/resources/images/projects/needleman-wunsch/example.png"]
                        }

                }
                ,
		{
                    "url":"http://jason-cowan.com/projects/word-ladder.html",
                    "http_code":200,
		    "direct_parent":"http://jason-cowan.com",
                    "content_type":"text/html",
                    "retrieval_time":120,
                    "io_error":false,
                    "malformed_url":false,
                    "timeout_error":false,
                    "casting_error":false,
                    "content_length":3108,
                    "last_modified":1389855143000,
                    "referencing_urls":[
                                "http://jason-cowan.com",
                                "http://jason-cowan.com/projects.html"
                    ],
                    "html_asset":{
                            "document_type":"&lt;!DOCTYPE html&gt;",
                            "title":"Word Ladder",
                            "description":"",
                            "misspellings":["Cowan","dataset","GUI&#39;s","screenshot","traversal","screenshot","Cowan"],
                            "at_mentions":[],
                            "hash_tags":[],
                            "emails":[],
                            "deprecated_tags":[],
                            "poor_link_naming":[],
                            "inputs_no_labels":[
                            ],
                            "no_alt_text":["http://jason-cowan.com/resources/images/cat.png","http://jason-cowan.com/resources/images/li.png"]
                        }

                }
                ,
		{
                    "url":"http://umt.edu",
                    "http_code":200,
		    "direct_parent":"http://jason-cowan.com",
                    "content_type":"text/html; charset=UTF-8",
                    "retrieval_time":243,
                    "io_error":false,
                    "malformed_url":false,
                    "timeout_error":false,
                    "casting_error":false,
                    "content_length":-1,
                    "last_modified":0,
                    "referencing_urls":[
                                "http://jason-cowan.com"
                    ],
                    "html_asset":{
                            "document_type":"",
                            "title":"",
                            "description":"",
                            "misspellings":[],
                            "at_mentions":[],
                            "hash_tags":[],
                            "emails":[],
                            "deprecated_tags":[],
                            "poor_link_naming":[],
                            "inputs_no_labels":[
                            ],
                            "no_alt_text":[]
                        }

                }
                ,
		{
                    "url":"http://www.gamescom-cologne.com/en/gamescom/home/index.php",
                    "http_code":302,
		    "direct_parent":"http://jason-cowan.com/projects/mario-runs.html",
                    "content_type":"text/html; charset=UTF-8",
                    "retrieval_time":3024,
                    "io_error":false,
                    "malformed_url":false,
                    "timeout_error":false,
                    "casting_error":false,
                    "content_length":-1,
                    "last_modified":0,
                    "referencing_urls":[
                                "http://jason-cowan.com/projects/mario-runs.html"
                    ],
                    "html_asset":null
                }
                ,
		{
                    "url":"http://jason-cowan.com/resources/images/projects/mario-runs/map.png",
                    "http_code":200,
		    "direct_parent":"http://jason-cowan.com/projects/mario-runs.html",
                    "content_type":"image/png",
                    "retrieval_time":228,
                    "io_error":false,
                    "malformed_url":false,
                    "timeout_error":false,
                    "casting_error":false,
                    "content_length":195490,
                    "last_modified":1389855143000,
                    "referencing_urls":[
                                "http://jason-cowan.com/projects/mario-runs.html"
                    ],
                    "html_asset":null
                }
                ,
		{
                    "url":"http://jason-cowan.com/resources/images/homepage/chart-which.png",
                    "http_code":200,
		    "direct_parent":"http://jason-cowan.com",
                    "content_type":"image/png",
                    "retrieval_time":245,
                    "io_error":false,
                    "malformed_url":false,
                    "timeout_error":false,
                    "casting_error":false,
                    "content_length":747286,
                    "last_modified":1389855143000,
                    "referencing_urls":[
                                "http://jason-cowan.com"
                    ],
                    "html_asset":null
                }
                ,
		{
                    "url":"http://jason-cowan.com/resources/images/projects/immuno/blue1.png",
                    "http_code":200,
		    "direct_parent":"http://jason-cowan.com/projects/immuno.html",
                    "content_type":"image/png",
                    "retrieval_time":229,
                    "io_error":false,
                    "malformed_url":false,
                    "timeout_error":false,
                    "casting_error":false,
                    "content_length":188572,
                    "last_modified":1389855143000,
                    "referencing_urls":[
                                "http://jason-cowan.com/projects/immuno.html"
                    ],
                    "html_asset":null
                }
                ,
		{
                    "url":"http://life.umt.edu/sait/",
                    "http_code":200,
		    "direct_parent":"http://jason-cowan.com",
                    "content_type":"text/html",
                    "retrieval_time":307,
                    "io_error":false,
                    "malformed_url":false,
                    "timeout_error":false,
                    "casting_error":false,
                    "content_length":-1,
                    "last_modified":0,
                    "referencing_urls":[
                                "http://jason-cowan.com"
                    ],
                    "html_asset":{
                            "document_type":"",
                            "title":"",
                            "description":"",
                            "misspellings":[],
                            "at_mentions":[],
                            "hash_tags":[],
                            "emails":[],
                            "deprecated_tags":[],
                            "poor_link_naming":[],
                            "inputs_no_labels":[
                            ],
                            "no_alt_text":[]
                        }

                }
                ,
		{
                    "url":"http://jason-cowan.com/resources/images/projects/immuno/red2.png",
                    "http_code":200,
		    "direct_parent":"http://jason-cowan.com/projects/immuno.html",
                    "content_type":"image/png",
                    "retrieval_time":250,
                    "io_error":false,
                    "malformed_url":false,
                    "timeout_error":false,
                    "casting_error":false,
                    "content_length":100051,
                    "last_modified":1389855143000,
                    "referencing_urls":[
                                "http://jason-cowan.com/projects/immuno.html"
                    ],
                    "html_asset":null
                }
                ,
		{
                    "url":"https://github.com/jcow/Mario-Runs-Visualization",
                    "http_code":200,
		    "direct_parent":"http://jason-cowan.com/projects.html",
                    "content_type":"text/html; charset=utf-8",
                    "retrieval_time":526,
                    "io_error":false,
                    "malformed_url":false,
                    "timeout_error":false,
                    "casting_error":false,
                    "content_length":27676,
                    "last_modified":0,
                    "referencing_urls":[
                                "http://jason-cowan.com/projects.html"
                    ],
                    "html_asset":{
                            "document_type":"",
                            "title":"",
                            "description":"",
                            "misspellings":[],
                            "at_mentions":[],
                            "hash_tags":[],
                            "emails":[],
                            "deprecated_tags":[],
                            "poor_link_naming":[],
                            "inputs_no_labels":[
                            ],
                            "no_alt_text":[]
                        }

                }
                ,
		{
                    "url":"http://jason-cowan.com/resources/images/projects/immuno/blue2.png",
                    "http_code":200,
		    "direct_parent":"http://jason-cowan.com/projects/immuno.html",
                    "content_type":"image/png",
                    "retrieval_time":258,
                    "io_error":false,
                    "malformed_url":false,
                    "timeout_error":false,
                    "casting_error":false,
                    "content_length":160629,
                    "last_modified":1389855143000,
                    "referencing_urls":[
                                "http://jason-cowan.com/projects/immuno.html"
                    ],
                    "html_asset":null
                }
                ,
		{
                    "url":"http://jason-cowan.com/resources/images/projects/triple_triad/stats.png",
                    "http_code":200,
		    "direct_parent":"http://jason-cowan.com/projects/triple-triad.html",
                    "content_type":"image/png",
                    "retrieval_time":261,
                    "io_error":false,
                    "malformed_url":false,
                    "timeout_error":false,
                    "casting_error":false,
                    "content_length":6092,
                    "last_modified":1389855143000,
                    "referencing_urls":[
                                "http://jason-cowan.com/projects/triple-triad.html"
                    ],
                    "html_asset":null
                }
                ,
		{
                    "url":"https://github.com/jcow/Immunofluorescence-Light-Correction",
                    "http_code":200,
		    "direct_parent":"http://jason-cowan.com/projects.html",
                    "content_type":"text/html; charset=utf-8",
                    "retrieval_time":421,
                    "io_error":false,
                    "malformed_url":false,
                    "timeout_error":false,
                    "casting_error":false,
                    "content_length":33624,
                    "last_modified":0,
                    "referencing_urls":[
                                "http://jason-cowan.com/projects.html",
                                "http://jason-cowan.com/projects/immuno.html"
                    ],
                    "html_asset":{
                            "document_type":"",
                            "title":"",
                            "description":"",
                            "misspellings":[],
                            "at_mentions":[],
                            "hash_tags":[],
                            "emails":[],
                            "deprecated_tags":[],
                            "poor_link_naming":[],
                            "inputs_no_labels":[
                            ],
                            "no_alt_text":[]
                        }

                }
                ,
		{
                    "url":"http://m.gamescom-cologne.com",
                    "http_code":301,
		    "direct_parent":"http://www.gamescom-cologne.com/en/gamescom/home/index.php",
                    "content_type":"text/html; charset=iso-8859-1",
                    "retrieval_time":811,
                    "io_error":false,
                    "malformed_url":false,
                    "timeout_error":false,
                    "casting_error":false,
                    "content_length":348,
                    "last_modified":0,
                    "referencing_urls":[
                                "http://www.gamescom-cologne.com/en/gamescom/home/index.php"
                    ],
                    "html_asset":null
                }
                
        ]
}